#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct SPageFilePhysics {
    pub packetId: i32,
    pub gas: f32,
    pub brake: f32,
    pub fuel: f32,
    pub gear: i32,
    pub rpms: i32,
    pub steerAngle: f32,
    pub speedKmh: f32,
    pub velocity: [f32; 3],
    pub accG: [f32; 3],
    pub wheelSlip: [f32; 4],
    pub wheelLoad: [f32; 4],
    pub wheelsPressure: [f32; 4],
    pub wheelAngularSpeed: [f32; 4],
    pub tyreWear: [f32; 4],
    pub tyreDirtyLevel: [f32; 4],
    pub tyreCoreTemperature: [f32; 4],
    pub camberRAD: [f32; 4],
    pub suspensionTravel: [f32; 4],
    pub drs: f32,
    pub tc: f32,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub cgHeight: f32,
    pub carDamage: [f32; 5],
    pub numberOfTyresOut: i32,
    pub pitLimiterOn: i32,
    pub abs: f32,
    pub kersCharge: f32,
    pub kersInput: f32,
    pub autoShifterOn: i32,
    pub rideHeight: [f32; 2],
    pub turboBoost: f32,
    pub ballast: f32,
    pub airDensity: f32,
    pub airTemp: f32,
    pub roadTemp: f32,
    pub localAngularVel: [f32; 3],
    pub finalFF: f32,
    pub performanceMeter: f32,
    pub engineBrake: i32,
    pub ersRecoveryLevel: i32,
    pub ersPowerLevel: i32,
    pub ersHeatCharging: i32,
    pub ersIsCharging: i32,
    pub kersCurrentKJ: f32,
    pub drsAvailable: i32,
    pub drsEnabled: i32,
    pub brakeTemp: [f32; 4],
    pub clutch: f32,
    pub tyreTempI: [f32; 4],
    pub tyreTempM: [f32; 4],
    pub tyreTempO: [f32; 4],
    pub isAIControlled: i32,
    pub tyreContactPoint: [[f32; 3]; 4],
    pub tyreContactNormal: [[f32; 3]; 4],
    pub tyreContactHeading: [[f32; 3]; 4],
    pub brakeBias: f32,
    pub localVelocity: [f32; 3],
    pub P2PActivations: i32,
    pub P2PStatus: i32,
    pub currentMaxRpm: i32,
}
