[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
  "-Ctarget-feature=-crt-static",
  "-Clink-args=-Wl,--allow-multiple-definition",
]
